### ISSUE TITLE
DeleteTR - Delete Trust Relation endpoint

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/inbound-saml#104]
### Success

1. ❌ Receive **DeleteTR** request
2. ❌ Validate external request data match request schema (has all needed required fields)
3. ❌ Save `TR` 
4. ❌ Respond with **success**

### Exceptions

1. ❌ throw `InvalidRequestError` if external request data validation fails
2. ❌ throw `PersistenceError` if fails to delete `TR` 

## Tasks

- [ ] Create Controller (handle request, throws `InvalidRequestError`)
- [ ] Create Interactor (service) (execute action)
- [ ] Create repository (persistence, throws `PersistenceError`)
- [ ] Create Façade (sync)
- [ ] Create server endpoint

**Comment by christian-hawk** [comment]
CRUD operations are done directly to oxtrust/config apis that handle persistence. Closing.
