### ISSUE TITLE
GetRemoteIDP

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/inbound-saml#13]
### Success

1. ✅ Receive **GetRemoteIdp** request
2. ✅ **Validate** external request data match request schema (has all required fields)
3. ✅ **Query** `IdpProvider` 
4. ✅ **Respond** with`IdpProvider`

### Exceptions

1. ✅ throw `InvalidRequestError` if external request data validation fails
2. ✅ throw `PersistenceError` if fails to query `IdpProvider`

## Tasks

- [x] Create Controller (handle request, throws `InvalidRequestError`)
- [x] Create service (execute action)
- [x] Create repository (persistence, throws `PersistenceError`)
