### ISSUE TITLE
GenerateSPMetadata

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/inbound-saml#30]
### Success

1. ❌ Receive **GenerateSPMetadata** request
2. ❌ Validate external request data match request schema (has all needed required fields)
3. ❌ Generates metadata 
4. ❌ Respond with metadata

### Exceptions

1. ❌ throw `InvalidRequestError` if external request data validation fails
2. ❌ throw `SpMetadataGenerationError` if fails to generate `SpMetadata` 
3. ❌ return `400` or `500` error code depending on error thrown

## Tasks
- [ ] Create SpProxy aggregate root (that contains configuration value object)
- [ ] Create SpProxyConfig value object (schema) that validates itself
- [ ] Create `SpMetadata` value object (schema) that validates itself
- [ ] Create `SpMetadata ` validator 
- [ ] Create Controller (handle request, throws `InvalidRequestError`)
- [ ] Presenter (aka dispatcher): dispatch response
- [ ] Create use-case interactor (aka service) (execute action)
- [ ] Create gateway  (external process, throws `SpMetadataGenerationError `)
- [ ] Create route on express (returns 500 if  `SpMetadataGenerationError `, 400 if `InvalidRequestError` thrown)

## Acceptance
```gherkin
Feature: Expose SP Metadata

Scenario: Successfully fetching metadata from endpoint

Given server is running
  And proxy have valid configuration
When "/sp/metadata" is called
Then endpoint should return metadata file according to configuration
```
