### ISSUE TITLE
GetTrustRelation - by id

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/inbound-saml#48]
### Success

1. ❌ Receive get **TrustRelation** request with id
2. ❌ **Validate** external request data match request schema (has all required fields)
3. ❌ **Query** `TrustRelationship `
4. ❌ **Respond** with`IdpProvider`

### Exceptions

1. ❌ throw `InvalidRequestError` if external request data validation fails
2. ❌ throw `PersistenceError` if fails to query `TrustRelation`

## Tasks

- [x] Create interactor (service) (execute action)
- [ ] Create Controller (handle request, throws `InvalidRequestError`)
- [ ] Create Presenter (dispatch response)
- [ ] Create repository (persistence, throws `PersistenceError`)

**Comment by christian-hawk** [comment]
closed as persistence should be handled by oxtrust/config api.
