### ISSUE TITLE
GetTrustRelation by host

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/inbound-saml#55]
### Success

1. ❌ Receive get **TrustRelation** request with host as param
2. ❌ **Validate** external request data match request schema (has all required fields)
3. ❌ **Query** `TrustRelationship `
4. ❌ **Respond** with`TrustRelationship` entity

### Exceptions

1. ❌ throw `InvalidRequestError` if external request data validation fails
2. ❌ throw `PersistenceError` if fails to query `TrustRelation`

## Tasks

- [ ] Create interactor (service) (execute action)
- [ ] Create Controller (handle request, throws `InvalidRequestError`)
- [ ] Create Presenter (dispatch response)
- [ ] Create repository (persistence, throws `PersistenceError`)
- [ ] Create Facade
