### ISSUE TITLE
Add Loggers 

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/inbound-saml#71]
In order of priority

- [ ] Add logger to error handlers
- [ ] Add logger decorator to controller requests
- [ ] Add logger debug decorator to all called functions
