### ISSUE TITLE
GetSpProxyConfig: get proxy configuration

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/inbound-saml#80]
### Success

1. ✅ Receive get **SpProxyConfig** request with no body (no params)
2. ✅ **Validate** external request data match request schema (has all required fields)
3. ✅ **Read** `SpProxyConfig `
4. ✅ **Respond** with `SpProxyConfig `

### Exceptions

1. ✅ throw `PersistenceError` if fails to read `SpProxyConfig`

## Tasks

- [x] Create interactor (service) (execute action)
- [x] Create Controller (handle request, throws `InvalidRequestError`)
- [x] Create Presenter (dispatch response)
- [x] Create repository (persistence, throws `PersistenceError`)
